[project]
name = "delivery_n"
version = "1.0.0"
description = "Flask app with root-level code."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
